### ISSUE TITLE
gray scale

### ISSUE THREAD

**Issue by haimmm** [gabriel-dev/rune-breaker#1]
Hi! I'm trying to follow your steps to do the same by myself. 
I'm currently stuck on the "transfer the image into gray scale".
I've been reading about several rgb to grayscale algorithms, and how to use hsv.
I have nice results with "easy to see" runes, but terrible results with the hard ones where the arrows are similar to the background in term of contrasts.. can you give me some tips about that part?

Thanks!

**Comment by gbrlfaria** [comment]
Hello, @haimmm. I hope you are doing well during the pandemic.

How are you converting your images to grayscale? And can you define what these "terrible results" are? Here's an example of a "hard to see" image that turned out okay when applying adaptive thresholding.

![](https://i.imgur.com/0odBcBZ.png)

The way the conversion is done in the project is kind of a hack. The formula used for BGR is used for HSV.
```py
# Color transform
img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
```
The calculation of the grayscale channel is described [here](https://docs.opencv.org/master/de/d25/imgproc_color_conversions.html). It should be the following for HSV.
```
Gray = 0.114*H + 0.587*S + 0.299*V
```
Although it works pretty well, I think it could be better. As I've said [here](https://github.com/gabriel-dev/rune-breaker#transforming-the-input), ~the most important channel when determining the shape of the arrow is the hue channel~, which sort of contradicts this formula. Thus, I am currently studying other combinations like the following one.
```py
img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

coefficients = [0.7, 0.2, 0.1] # [H, S, V]
img = cv2.transform(img, np.array(coefficients).reshape((1, 3)))
```
You can mess with these coefficients until you get the desired results. I should update the project one last time this week after I find the optimal values (it's really tiresome to run the project and then update all the information in the README).

----

**EDIT**
After running some tests, I have to correct some of my statements. It looks like the optimal grayscale algorithm doesn't really weight the hue channel as much. Here's a [list](https://pastebin.com/CdhrzcHK) with many different coefficients and their respective number of misses. A miss occurs when the arrow locating algorithm returns the center of the search area. 

Running a simple genetic algorithm to find the values that minimize the number of misses, I got the following results.
```
Gray = 0.0445*H + 0.6568*S + 0.2987*V
```
Interestingly enough, these values are very close to the ones used by the default `BGR2GRAY` algorithm. Anyway, I'll continue to optimize the values in the preprocessing stage. When I get everything done, I'll push the changes to the repository.

**Comment by gbrlfaria** [comment]
I am closing this issue since it has been inactive for the last week. Anyway, I have rewritten the article section that discusses the grayscale transformation so that it is easier to understand.

**Comment by haimmm** [comment]
Hi @gabriel-dev  thanks for the clear answers and sorry for not responding for a while.
To be honest, most of my experience is with java, and I was trying to make similar project but java based. But then I realized that probably python computer vision libraries will give me much better results and in less time, and i wanted to learn python anyway so i decided to just follow your cool project instead!
So i'm starting over now, still learning some python basics and gonna try to understand the "preprocess"   code that you wrote soon.

Do you have a discord or something where I can ask some noob questions? if that's not too much of course, thanks! :)

**Comment by gabriel-dev** [comment]
My discord is `fuzzy#8692`. Feel free to contact me over there. Just keep in mind that I may take some time to read your messages, but I'll do my best to assist you.
