### ISSUE TITLE
i have a problem while compile your project

### ISSUE THREAD

**Issue by tlazzang** [gabriel-dev/rune-breaker#2]
Hello, gabriel
I am sorry for my bad english and developing skill
when i try to compile and run preprocess.py, I see the log "Centroid not found! Returning the center point..."
every image can not find centroid how can i find it?

**Comment by gbrlfaria** [comment]
Hello, @tlazzang 

There is no reason to be sorry. As described in the fourth item of the [algorithm section](https://github.com/gabriel-dev/rune-breaker#algorithm) of the README, the program returns the **center point** of the searching area when no suitable contour is found. In other words, the algorithm is unable to find any outline that resembles a circle in the image. And that may be for many reasons. Maybe the input image you're using is incorrectly sized and the search regions are being misplaced (the software was created to deal with 800x600 screenshots and may fail in other cases), maybe there's some weird obfuscation of some sort, etc. 

If you can provide me with more details about the input image you're using, or even with the output of the preprocessing script, I may be able to further assist you.

**Comment by tlazzang** [comment]
Thank you very much for your kind reply.
I tried to preprocess image that you make("docs/input_image.png"). It works well.

But, when i try to preprocess image that I make(800x600 jpeg), i can not find any contour and center point.
I made image using ScrollLock Key to capture screenshot in game.
Differently from your image, in my image, some noise added to arrow circle area, i think it is reason why dose not works.

Is there a problem with the way I capture image?

below is my image to preprocess

![wide_dldd_2](https://user-images.githubusercontent.com/24838905/86078198-87099880-bac8-11ea-9fad-593cc4912b74.jpeg)

<img width="305" alt="ddd" src="https://user-images.githubusercontent.com/24838905/86084301-73b1f980-bad7-11ea-9159-9aabb9a2d108.png">

**Comment by gbrlfaria** [comment]
Your capture method seems to be just fine. As you've said, the runes from Ardentmill have some extra noise in comparison to the ones from regular maps (four different hue shifts and some scattered pixels). Unfortunately, the preprocessing algorithm was optimized for regular runes. That's probably why the thresholded image ends up garbled, often making the algorithm fail. But, you might get it working by doing some adjustments.

You can tweak some parameters of the preprocessing step, such as the [grayscale coefficients](https://github.com/gabriel-dev/rune-breaker/blob/revamp/preprocessing/preprocess.py#L103), the [adaptive threshold arguments](https://github.com/gabriel-dev/rune-breaker/blob/revamp/preprocessing/preprocess.py#L110), and even the [circle score threshold](https://github.com/gabriel-dev/rune-breaker/blob/revamp/preprocessing/preprocess.py#L175). Hopefully, this will make the outlines easier to identify.

If you fail to find a set of parameters that give you satisfactory results, I'm afraid you will have to try something else. One possible alternative is to use some AI-based method to locate the arrows given an input image, possibly using grayscale images as input instead of binarized ones.

**Comment by gbrlfaria** [comment]
Issue closed due to inactivity.
