### ISSUE TITLE
New runes, new challenges

### ISSUE THREAD

**Issue by DanTheTingler** [gabriel-dev/rune-breaker#4]
Hi Gabriel! I'm not sure if you've had a chance to take a look at runes after the most recent update, but it looks like Nexon has added some additional anti-bot measures; the arrows no longer have circles around them, and have had some an additional layer of obfuscation/noise randomly added above the arrows. Do you have any ideas on how to locate the arrows better without the circles?

I've attempted to re-train several models with the new runes, and even though I'm able to generate a model with a val_accuracy of ~85%, it's only able to identify around ~25% of arrows properly. I'e attached two cropped, but unprocessed screenshots of the new runes. Any ideas and/or would be greatly appreciated!

![rune-example-13](https://user-images.githubusercontent.com/8312662/91520955-7d739580-e8ab-11ea-8cbf-575954bdab41.png)
![rune-example-5](https://user-images.githubusercontent.com/8312662/91520960-7ea4c280-e8ab-11ea-9309-5c6eea844a4d.png)

**Comment by gbrlfaria** [comment]
Hi there, Daniel! Yes, I've seen the new updates. Quoting a few lines from the README:

> The second issue, on the other hand, is trickier. First, there is software capable of bypassing the anti-botting system internally. Second, recent advancements in AI technology have been closing the gap between humans and machines. Even though it is simple to patch the game visuals and prevent this project from functioning, **it is just as easy to make it work again**.

And that is precisely the case here. There are actually many feasible approaches to both locate and classify arrows now. Some of them include filtering pixels by color, filtering contours by area, analyzing contour shapes, and template matching. Alternatively, you can go full machine learning and create models to both locate and classify the arrows on the screen, as I mentioned in the README.

Unfortunately, I don't have any plans to update this repository, so that's something you and others will have to try by yourselves.

**Comment by DanTheTingler** [comment]
Got it, thanks Gabriel! You've given me some excellent avenues to explore, so I'll be taking a look into what you've suggested. Your reply and your help is greatly appreciated!
